spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://postgres:5432/movie
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  rabbitmq:
    host: rabbitmq
    password: guest
    port: 15672
    username: guest
server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
